name: Build Packer Vagrant Box

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PACKER_VERSION: "1.8.6"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Check if Hyper-V tools installed
        run: |
          echo "::debug " $((Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V))

      - name: Restore Packer Cache
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/packer_cache
          key: ${{ runner.os }}-packer-${{ hashFiles('**/truenas-scale.pkr.hcl') }}

      - name: Run `packer init`
        id: init
        run: "packer init ./truenas-scale.pkr.hcl"
          
      - name: Build Vagrant Box
        run: |
          packer build -only="hyperv-iso.truenas-scale-amd64" -color=false -on-error=abort -timestamp-ui truenas-scale.pkr.hcl
        env:
          PKR_VAR_vagrant_box: truenas-scale-22.1-amd64-hyperv.box